configfile: "config/config.yaml"

rule all:
    input:
        "results/{batch}_af_matrix.csv".format(batch=config['batch_name'])



## Modules

include: "rules/mutect2.smk"
include: "rules/format-data.smk"
