import argparse
import json
import os

from kneed import KneeLocator


def collect_data(input_path: str) -> tuple[list[int], list[int]]:
    """
    Reads .JSON file generated by fastBE clustering algorithm and extracts the number of clones and their corresponding objective values.

        Args:
            input_path (str): The relative path to the .JSON file containing the metadata from fastBE cluster.

        Returns:
            tuple: A tuple containing two lists: the first list contains the number of clones, and the second list contains the corresponding objective values.

    Note:
        - If the file does not exist or if no valid .JSON files are found, the function will return two empty lists.
    """

    number_of_clones = []
    objective_value = []

    if os.path.isfile(input_path):
            if input_path.endswith('.json'):
                with open(input_path, 'r') as f:
                    data = json.load(f)
                if 'num_clusters' in data and 'objective_values' in data:
                    number_of_clones = [i for i in range(data.get('num_clusters'))]
                    objective_value = data.get('objective_values')
            else:
                print(f"Error: {input_path} is not a JSON file.")
                return [], []

    return number_of_clones, objective_value


# Returns the knee point of the curve given the number of clones and their corresponding objective values. If either list is empty, it returns None.
def find_knee_point(number_of_clones: list[int], objective_value: list[int]) -> int:
    if not number_of_clones or not objective_value:
        return None
    kn = KneeLocator(number_of_clones, objective_value, curve='convex', direction='decreasing')
    return kn.knee




if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Find the knee point...')
    parser.add_argument('-i', '--input', help="input path to your JSON cluster directory")
    parser.add_argument('-o', '--output', help="output path to .txt file containing optimal clones")
    args = parser.parse_args()

    if args.input:
        x, y = collect_data(args.input)
        if x and y:
            knee_point = find_knee_point(x, y)
            print(f"The knee point is at {knee_point} clones.")
            if args.output:
                with open(args.output, "w") as f:
                    f.write(str(knee_point))
        else:
            print("No valid data found in the provided directory.")
