from kneed import KneeLocator
import os
import json
import argparse

def collect_data(directory_path: str) -> tuple[list[int], list[int]]:
    """
    Reads .JSON file generated by fastBE clustering algorithm and extracts the number of clones and their corresponding objective values.

        Args:
            directory_path (str): The path to the directory containing the .JSON files.

        Returns:
            tuple: A tuple containing two lists: the first list contains the number of clones, and the second list contains the corresponding objective values.

    Note:
        - If the directory does not exist or if no valid .JSON files are found, the function will return two empty lists.
    """

    number_of_clones = []
    objective_value = []

    if not os.path.isdir(directory_path):
        print(f"Error: {directory_path} is not a valid directory.")
        return [], []

    for file in os.listdir(directory_path):
        if file.endswith('.json'):
            with open(os.path.join(directory_path, file), 'r') as f:
                data = json.load(f)
            
            if 'num_clusters' in data and 'objective_values' in data:
                number_of_clones = [i for i in range(data.get('num_clusters'))]
                objective_value = data.get('objective_values')
                break 

    return number_of_clones, objective_value


# Returns the knee point of the curve given the number of clones and their corresponding objective values. If either list is empty, it returns None.
def find_knee_point(number_of_clones: list[int], objective_value: list[int]) -> int:
    if not number_of_clones or not objective_value:
        return None
    kn = KneeLocator(number_of_clones, objective_value, curve='convex', direction='decreasing')
    return kn.knee




if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Find the knee point...')
    parser.add_argument('-i', '--input', help="input path to your JSON cluster directory")
    args = parser.parse_args()

    if args.input:
        x, y = collect_data(args.input)     
        if x and y:
            knee_point = find_knee_point(x, y)
            print(f"The knee point is at {knee_point} clones.")
        else:
            print("No valid data found in the provided directory.")

    
