# SLURM cluster configuration for this workflow.
# Am example usage:
# snakemake -s Reconstruction-workflow.snakefile \
#   --latency-wait 60 --restart-times 2 --keep-going \
#   --cluster-config workflow/config/slurm_cluster.yaml \
#   --cluster "sbatch -p {cluster.partition} --mem={cluster.mem} -t {cluster.time} -c {cluster.ncpus} -n {cluster.ntasks} -o {cluster.output}" \
#   -j 100

__default__:
    partition: normal
    time: "08:00:00"
    mem: 16G
    ncpus: 4
    ntasks: 1
    output: logs/cluster/{rule}.%A.out


Mutect2:
    partition: highmem
    time: "24:00:00"
    mem: 20G
    ncpus: 4
    ntasks: 1
    output: logs/cluster/{rule}.%A_%a.out



vcf_converter:
    partition: MSC
    time: "00:03:00"
    mem: 2G
    ncpus: 1
    ntasks: 1
    output: logs/cluster/{rule}.%A.out
